// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.24.3
// source: plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolPlugin_Configure_FullMethodName   = "/plugin.ToolPlugin/Configure"
	ToolPlugin_Call_FullMethodName        = "/plugin.ToolPlugin/Call"
	ToolPlugin_GetToolInfo_FullMethodName = "/plugin.ToolPlugin/GetToolInfo"
	ToolPlugin_ListTools_FullMethodName   = "/plugin.ToolPlugin/ListTools"
)

// ToolPluginClient is the client API for ToolPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolPlugin is the service that all tool plugins must implement
type ToolPluginClient interface {
	// Configure passes plugin settings from HCL config
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Call invokes a tool on the plugin with the given payload
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// GetToolInfo returns metadata about a specific tool
	GetToolInfo(ctx context.Context, in *GetToolInfoRequest, opts ...grpc.CallOption) (*GetToolInfoResponse, error)
	// ListTools returns info for all tools this plugin provides
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
}

type toolPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewToolPluginClient(cc grpc.ClientConnInterface) ToolPluginClient {
	return &toolPluginClient{cc}
}

func (c *toolPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, ToolPlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolPluginClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, ToolPlugin_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolPluginClient) GetToolInfo(ctx context.Context, in *GetToolInfoRequest, opts ...grpc.CallOption) (*GetToolInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolInfoResponse)
	err := c.cc.Invoke(ctx, ToolPlugin_GetToolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolPluginClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ToolPlugin_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolPluginServer is the server API for ToolPlugin service.
// All implementations must embed UnimplementedToolPluginServer
// for forward compatibility.
//
// ToolPlugin is the service that all tool plugins must implement
type ToolPluginServer interface {
	// Configure passes plugin settings from HCL config
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Call invokes a tool on the plugin with the given payload
	Call(context.Context, *CallRequest) (*CallResponse, error)
	// GetToolInfo returns metadata about a specific tool
	GetToolInfo(context.Context, *GetToolInfoRequest) (*GetToolInfoResponse, error)
	// ListTools returns info for all tools this plugin provides
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	mustEmbedUnimplementedToolPluginServer()
}

// UnimplementedToolPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolPluginServer struct{}

func (UnimplementedToolPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedToolPluginServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedToolPluginServer) GetToolInfo(context.Context, *GetToolInfoRequest) (*GetToolInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolInfo not implemented")
}
func (UnimplementedToolPluginServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedToolPluginServer) mustEmbedUnimplementedToolPluginServer() {}
func (UnimplementedToolPluginServer) testEmbeddedByValue()                    {}

// UnsafeToolPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolPluginServer will
// result in compilation errors.
type UnsafeToolPluginServer interface {
	mustEmbedUnimplementedToolPluginServer()
}

func RegisterToolPluginServer(s grpc.ServiceRegistrar, srv ToolPluginServer) {
	// If the following call panics, it indicates UnimplementedToolPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolPlugin_ServiceDesc, srv)
}

func _ToolPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolPlugin_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolPluginServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolPlugin_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolPluginServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolPlugin_GetToolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolPluginServer).GetToolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolPlugin_GetToolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolPluginServer).GetToolInfo(ctx, req.(*GetToolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolPlugin_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolPluginServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolPlugin_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolPluginServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolPlugin_ServiceDesc is the grpc.ServiceDesc for ToolPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.ToolPlugin",
	HandlerType: (*ToolPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _ToolPlugin_Configure_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _ToolPlugin_Call_Handler,
		},
		{
			MethodName: "GetToolInfo",
			Handler:    _ToolPlugin_GetToolInfo_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ToolPlugin_ListTools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/plugin.proto",
}
